name: matsci465
channels:
  - defaults
  - conda-forge
dependencies:
  - anaconda_prompt=1.1.0=haa95532_1
  - anyio=4.10.0=py313haa95532_0
  - argon2-cffi=25.1.0=py313haa95532_0
  - argon2-cffi-bindings=25.1.0=py313h02ab6af_0
  - asttokens=3.0.0=py313haa95532_0
  - async-lru=2.0.5=py313haa95532_0
  - attrs=25.4.0=py313haa95532_2
  - aws-c-auth=0.8.0=h2219d47_15
  - aws-c-cal=0.8.1=h099ea23_3
  - aws-c-common=0.10.6=h2466b09_0
  - aws-c-compression=0.3.0=h099ea23_5
  - aws-c-event-stream=0.5.0=h85d8506_11
  - aws-c-http=0.9.2=h3888f84_4
  - aws-c-io=0.15.3=hc5a9e45_6
  - aws-c-mqtt=0.11.0=h2c94728_12
  - aws-c-s3=0.7.7=h6a38c86_0
  - aws-c-sdkutils=0.2.1=h099ea23_4
  - aws-checksums=0.2.2=h099ea23_4
  - aws-crt-cpp=0.29.7=h0642867_7
  - aws-sdk-cpp=1.11.458=h5f5f9c4_4
  - babel=2.17.0=py313haa95532_0
  - beautifulsoup4=4.14.2=py313haa95532_0
  - blas=1.0=mkl
  - bleach=6.3.0=py313haa95532_0
  - bokeh=3.8.1=pyhd8ed1ab_0
  - brotlicffi=1.2.0.0=py313h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2026.1.4=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=he9e932c_0
  - certifi=2026.01.04=py313haa95532_0
  - cffi=2.0.0=py313h02ab6af_1
  - charset-normalizer=3.4.4=py313haa95532_0
  - click=8.3.1=pyha7b4d00_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=py313haa95532_0
  - colorspacious=1.1.2=pyhecae5ae_1
  - comm=0.2.3=py313haa95532_0
  - contourpy=1.3.3=py313h214f63a_0
  - cycler=0.12.1=py313haa95532_0
  - cytoolz=1.1.0=py313h5ea7bf4_1
  - dask=2026.1.1=pyhcf101f3_0
  - dask-core=2026.1.1=pyhcf101f3_1
  - dask-image=2025.11.0=pyhd8ed1ab_0
  - debugpy=1.8.16=py313h885b0b7_1
  - decorator=5.2.1=py313haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.4.0=pyhcf101f3_1
  - distributed=2026.1.1=pyhcf101f3_1
  - emdfile=0.0.16=pyhd8ed1ab_1
  - executing=2.2.1=py313haa95532_0
  - expat=2.7.3=h885b0b7_4
  - filelock=3.20.3=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.61.0=py313h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - gdown=5.2.1=pyhd8ed1ab_0
  - graphite2=1.3.14=hd77b12b_1
  - h11=0.16.0=py313haa95532_1
  - h5py=3.15.1=nompi_py313hf7f959b_101
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.6=nompi_h89f0904_104
  - hdf5plugin=5.1.0=py313hb6a6b91_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py313haa95532_0
  - httpx=0.28.1=py313haa95532_1
  - hyperspy=2.3.0=pyhd8ed1ab_3
  - hyperspy-base=2.3.0=pyhd8ed1ab_3
  - hyperspy-gui-ipywidgets=2.1.0=pyhd8ed1ab_0
  - hyperspy-gui-traitsui=2.1.1=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=py313haa95532_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=6.31.0=py313h4442805_0
  - ipympl=0.9.8=pyhcf101f3_0
  - ipython=9.7.0=py313haa95532_0
  - ipython_pygments_lexers=1.1.1=py313haa95532_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - jedi=0.19.2=py313haa95532_0
  - jinja2=3.1.6=py313haa95532_0
  - joblib=1.5.3=pyhd8ed1ab_0
  - jpeg=9f=ha349fce_0
  - json5=0.12.1=py313haa95532_0
  - jsonschema=4.25.1=py313haa95532_0
  - jsonschema-specifications=2025.9.1=py313haa95532_0
  - jupyter-lsp=2.2.5=py313haa95532_0
  - jupyter_client=8.8.0=py313haa95532_0
  - jupyter_core=5.9.1=py313haa95532_0
  - jupyter_events=0.12.0=py313haa95532_1
  - jupyter_server=2.17.0=py313haa95532_0
  - jupyter_server_terminals=0.5.3=py313haa95532_0
  - jupyterlab=4.5.0=py313haa95532_0
  - jupyterlab_pygments=0.3.0=py313haa95532_0
  - jupyterlab_server=2.28.0=py313haa95532_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kiwisolver=1.4.9=py313h03f52e7_0
  - krb5=1.21.3=hdf4eb48_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20240722.0=cxx17_h4eb7d71_4
  - libaec=1.1.4=h20038f6_0
  - libarrow=18.1.0=h7377be5_4_cuda
  - libarrow-acero=18.1.0=hf0642a6_4_cuda
  - libarrow-dataset=18.1.0=hf0642a6_4_cuda
  - libarrow-substrait=18.1.0=h322cffe_4_cuda
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.18.0=h43ecb02_0
  - libdeflate=1.17=h2bbff1b_1
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_1
  - libgoogle-cloud=2.31.0=h07d40e7_0
  - libgoogle-cloud-storage=2.31.0=he5eb982_0
  - libgrpc=1.67.1=h7aa3b8a_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libmpdec=4.0.0=h827c3e9_0
  - libparquet=18.1.0=hbdea95a_4_cuda
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.28.2=hcaed137_0
  - libre2-11=2024.07.02=h4eb7d71_2
  - libsodium=1.0.20=h83e8143_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.21.0=hbe90ef8_0
  - libtiff=4.5.1=hd77b12b_0
  - libutf8proc=2.9.0=h2466b09_1
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - link-traits=1.0.3=pyhd8ed1ab_4
  - llvmlite=0.46.0=py313h5c49287_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py313hfab1156_1
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py313h827c3e9_0
  - matplotlib=3.10.8=py313haa95532_0
  - matplotlib-base=3.10.8=py313h26e45b9_0
  - matplotlib-inline=0.2.1=py313haa95532_0
  - mistune=3.1.2=py313haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py313h0b37514_0
  - mkl_fft=2.1.1=py313hbc2a22c_0
  - mkl_random=1.3.0=py313h42c1672_0
  - mpire=2.10.2=pyhd8ed1ab_1
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py313hf069bd2_1
  - mysql-common=9.3.0=hc394544_4
  - mysql-libs=9.3.0=h58c8544_4
  - narwhals=2.15.0=pyhcf101f3_0
  - natsort=8.4.0=pyh29332c3_1
  - nbclient=0.10.2=py313haa95532_0
  - nbconvert-core=7.16.6=py313haa95532_0
  - nbformat=5.10.4=py313haa95532_0
  - ncempy=1.14=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=py313haa95532_0
  - networkx=3.6.1=pyhcf101f3_0
  - notebook-shim=0.2.4=py313haa95532_0
  - numba=0.63.1=py313h2da9318_0
  - numexpr=2.14.1=py313h7660c64_0
  - numpy=2.3.5=py313h050da96_0
  - numpy-base=2.3.5=py313h1e017a8_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.6.0=h725018a_0
  - orc=2.0.3=h34659fe_0
  - packaging=25.0=py313haa95532_1
  - pandas=2.3.3=py313hc90dcd4_2
  - pandocfilters=1.5.1=py313haa95532_0
  - parso=0.8.5=py313haa95532_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.46=h5740b90_0
  - pentapy=1.4.1=py313h0591002_0
  - pillow=11.1.0=py313h096bfcc_0
  - pims=0.7=pyhd8ed1ab_1
  - pint=0.25.2=pyhcf101f3_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.0=py313haa95532_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - prettytable=3.17.0=pyhd8ed1ab_0
  - prometheus_client=0.21.1=py313haa95532_0
  - prompt-toolkit=3.0.52=py313haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py313h02ab6af_1
  - pure_eval=0.2.3=py313haa95532_0
  - py4dstem=0.14.14=pyhd8ed1ab_0
  - pyaml=25.7.0=pyhe01879c_0
  - pyarrow=18.1.0=py313hfa70ccb_0
  - pyarrow-core=18.1.0=py313h0d32010_0_cuda
  - pybaselines=1.2.1=pyhd8ed1ab_0
  - pycparser=2.23=py313haa95532_0
  - pyface=8.0.0=pyhd8ed1ab_2
  - pygments=2.19.2=py313haa95532_0
  - pylops=2.6.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=py313haa95532_0
  - pyqt=6.9.1=py313h12ec796_0
  - pyqt6-sip=13.10.2=py313h630b2a1_0
  - pysocks=1.7.1=py313haa95532_1
  - python=3.13.11=h260b955_100_cp313
  - python-box=7.3.2=py313h5ea7bf4_1
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python-fastjsonschema=2.21.2=py313haa95532_0
  - python-json-logger=4.0.0=py313haa95532_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.13=3_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py313h885b0b7_0
  - pywin32-on-windows=0.1.0=pyh07e9846_2
  - pywinpty=2.0.15=py313h72d21ff_0
  - pyyaml=6.0.3=py313hb9a58be_0
  - pyzmq=27.1.0=py313h7149c55_1
  - qtbase=6.9.2=h06bae2a_5
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - re2=2024.07.02=haf4117d_2
  - referencing=0.37.0=py313haa95532_0
  - requests=2.32.5=py313haa95532_1
  - rfc3339-validator=0.1.4=py313haa95532_0
  - rfc3986-validator=0.1.1=py313haa95532_0
  - rosettasciio-base=0.12.0=py313h5ea7bf4_0
  - rpds-py=0.28.0=py313h114bc41_0
  - ruamel.yaml=0.19.1=pyhcf101f3_0
  - ruamel.yaml.clib=0.2.15=py313h5fd188c_1
  - scikit-learn=1.8.0=np2py313h4ce4a18_1
  - scikit-optimize=0.10.2=pyhd8ed1ab_1
  - scipy=1.16.3=py313hbd6d557_0
  - send2trash=1.8.3=py313haa95532_0
  - setuptools=80.9.0=py313haa95532_0
  - sip=6.12.0=py313h706e071_0
  - six=1.17.0=py313haa95532_0
  - slicerator=1.1.0=pyhd8ed1ab_1
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=py313haa95532_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.5=py313haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - stack_data=0.6.3=py313haa95532_0
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tblib=3.2.2=pyhcf101f3_0
  - terminado=0.18.1=py313haa95532_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2025.12.20=py313haa95532_0
  - tinycss2=1.4.0=py313haa95532_0
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhcf101f3_3
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py313h02ab6af_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py313haa95532_0
  - traits=7.1.0=py313h5ea7bf4_0
  - traitsui=8.0.0=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py313haa95532_0
  - typing_extensions=4.15.0=py313haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.3=py313haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=py313haa95532_0
  - webencodings=0.5.1=py313haa95532_2
  - websocket-client=1.8.0=py313haa95532_0
  - wheel=0.45.1=py313haa95532_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=py313haa95532_1
  - winpty=0.4.3=4
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - scikit-image==0.26.0
prefix: C:\anacoda\envs\matsci465
